apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: satya
  name: satya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: satya
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - name: nfs-share
            # mount point in container
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nfs-share
          persistentVolumeClaim:
            # PVC name you created
            claimName: nfs-pvc
status: {}