apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: satya-dep
  name: satya-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satya-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: satya-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        envFrom:
        - secretRef:
            name: test-secret
status: {}