apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      demotype: nginx-daemonset-test
  template:
    metadata:
      labels:
        demotype: nginx-daemonset-test
    spec:
      containers:
      - image: nginx
        name: nginx