apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # add this to /etc/hosts
  # your load balancer ip test.batpool.com
  - host: "test.batpool.com"
    http:
      paths:
      - pathType: Prefix
        path: "/svc"
        backend:
          service:
            name: service
            port:
              number: 80
      - pathType: Prefix
        path: "/svc1"
        backend:
          service:
            name: service1
            port:
              number: 80
