apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
status:
  loadBalancer: {}
